name: Build APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-apk:
    runs-on: ubuntu-latest
    timeout-minutes: 90
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        
    - name: Install system dependencies
      run: |
        sudo apt-get update -y
        sudo apt-get install -y \
          git zip unzip \
          openjdk-17-jdk \
          autoconf libtool pkg-config \
          zlib1g-dev libncurses5-dev \
          libncursesw5-dev libtinfo5 \
          cmake libffi-dev libssl-dev \
          python3-setuptools \
          build-essential
          
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --user buildozer cython==0.29.36 virtualenv
        echo "$HOME/.local/bin" >> $GITHUB_PATH
        
    - name: Create Buildozer spec
      run: |
        cat > buildozer.spec <<EOL
[app]
title = MyApp
package.name = myapp
package.domain = org.test
source.dir = .
source.include_exts = py,png,jpg,kv,atlas
version = 1.0.0
requirements = python3==3.10.13,kivy==2.3.0
orientation = portrait
osx.python_version = 3
osx.kivy_version = 2.3.0
android.api = 33
android.minapi = 21
android.sdk = 24
android.ndk = 25b
p4a.branch = master
android.arch = arm64-v8a
EOL
        
    - name: Run Buildozer
      run: |
        buildozer -v android release
        
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: android-app
        path: bin/*.apk
